apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
#  namespace: kube-system
  namespace: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: bob-user-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bob
  namespace: default
