apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "" 
  namespace: ""  
subjects:
    - kind: User
      name: dave
      apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: ""
  apiGroup: rbac.authorization.k8s.io
