kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: none-role
  namespace: ""
subjects:
- kind: User
  name: dave
  apiGroup: ""
roleRef:
  kind: Role
  name: none
  apiGroup: ""
