apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx
  labels:
    app: nginx 
    tier: nginx
spec:
  replicas: 3 
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
        app: nginx
    spec:
      containers:
      - name: server
        image: luliyan/nginx:v1 
        ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: nginx
    targetPort: 80
