apiVersion: v1 
kind: Pod 
metadata:
  name: web
  labels:
    app: webapp 
spec:
  volumes:
  - name: app
    emptyDir: {}
  containers: 
    - name: web-my
      image: luliyan/for_hw_otus:latest
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
  - name: init-myservice
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts: 
      - name: app
        mountPath: /app

